# Generated by Django 3.1.1 on 2020-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='description',
            field=models.TextField(default='quite ok'),
            preserve_default=False,
        ),
    ]
