# Generated by Django 3.1.1 on 2020-12-14 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_cities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
