# Generated by Django 3.1.1 on 2020-12-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_cities_pub_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cities',
            table='CITIES',
        ),
    ]
