# Generated by Django 3.1.2 on 2020-12-15 16:02

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201215_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social_security', fernet_fields.fields.EncryptedTextField(max_length=10)),
                ('my_issue', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='pub_date',
        ),
    ]
